### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by Taverz** [Livinglist/Manji#12]
when the application starts, it is always loaded.
Android.
when debugging, the last message he got stuck on
`E/        (17598): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
E/        (17598): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]`

**Comment by Livinglist** [comment]
Hi Taverz, thanks for reaching out.

Do you have the dictionary file under manji/data/dictDB.db? The dictDB file size is about 169mb, if not you could try fetching the file by running `git lfs pull` in the project folder.

**Comment by Taverz** [comment]
The database I had I once again cloned the repository and did  **git lfs pull** , but no changes. Maybe I did something wrong with **google_api_credentials.dart** , can it be left blank or filled in somehow? do you need to install something?

**Comment by Livinglist** [comment]
> The database I had I once again cloned the repository and did **git lfs pull** , but no changes. Maybe I did something wrong with **google_api_credentials.dart** , can it be left blank or filled in somehow? do you need to install something?

No that shouldn't be the problem. What's the version of Android you are trying to run the app on? And also can i have the output of `flutter doctor -v`

**Comment by Taverz** [comment]
If it helps - successfully launched other applications.
Emulator- API 28 / Android 9.0
![Скриншот 25-03-2021 080907](https://user-images.githubusercontent.com/55701501/112422386-d8864180-8d41-11eb-8a3a-cfc6b3cdb22e.jpg)

**Comment by Livinglist** [comment]
> If it helps - successfully launched other applications.
> Emulator- API 28 / Android 9.0
> ![Скриншот 25-03-2021 080907](https://user-images.githubusercontent.com/55701501/112422386-d8864180-8d41-11eb-8a3a-cfc6b3cdb22e.jpg)

I assume you already have the `google-services.json` under android/app/, can you make sure that you have the same applicationId inside android/app/build.gradle and the your firebase project.

A really dumb way to fix this is just try to create a new project, and copy all the stuff from these folders: lib, data, fonts, font_awesome_flutter, and also the both the project-level and app-level `build.gradle` files (replace my applicationId `jiaqifeng.kanji_dictionary` with yours), and lastly `pubspec.yaml` file.

**Comment by Taverz** [comment]
before that, the **applicationId**  was **jiaqifeng.kanji_dictionary** and did not work.
I changed the SDK version to 30 and turned on analytics in firebase(I don’t know what changed it), but it worked.
Thanks for the advice and help, very nice. 
I love the app and its design.

**Comment by Livinglist** [comment]
> before that, the **applicationId** was **jiaqifeng.kanji_dictionary** and did not work.
> I changed the SDK version to 30 and turned on analytics in firebase(I don’t know what changed it), but it worked.
> Thanks for the advice and help, very nice.
> I love the app and its design.

Glad it worked!
